[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/admin"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/dispatcher"
to = "/dispatcher/index.html"
status = 200

[[redirects]]
from = "/dispatcher/*"
to = "/dispatcher/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://easypdf-backend-2xhr.onrender.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
