export const refs = {
  statsTabButtons: document.querySelectorAll('[data-stats-tab-target]'),
  statsTabScreens: document.querySelectorAll('[data-stats-tab-screen]'),
  statsMonth: document.getElementById('statsMonth'),
  statsPlanValue: document.getElementById('statsPlanValue'),
  statsUsageValue: document.getElementById('statsUsageValue'),
  statsRemainingValue: document.getElementById('statsRemainingValue'),
  statsOrdersValue: document.getElementById('statsOrdersValue'),
  statsGeneratedValue: document.getElementById('statsGeneratedValue'),
  statsUsageBar: document.getElementById('statsUsageBar'),
  statsUsagePercent: document.getElementById('statsUsagePercent'),
  statsRing: document.getElementById('statsRing'),
  statsRingValue: document.getElementById('statsRingValue'),
  statsQuotaLabel: document.getElementById('statsQuotaLabel'),
  statsActivitySummary: document.getElementById('statsActivitySummary'),
  statsActivityBars: document.getElementById('statsActivityBars'),
  statsStatusSummary: document.getElementById('statsStatusSummary'),
  statsStatusStack: document.getElementById('statsStatusStack'),
  statsStatusLegend: document.getElementById('statsStatusLegend'),
  statsPlanLimit: document.getElementById('statsPlanLimit'),
  statsPlanBar: document.getElementById('statsPlanBar'),
  statsForecastVolume: document.getElementById('statsForecastVolume'),
  statsForecastDate: document.getElementById('statsForecastDate'),
};
