export const SUPPORTED_LANGUAGES = new Set(['uk', 'en', 'cs']);

export const TRANSLATIONS = {
  uk: {
    app_name: 'DocTra',
    offer_title: 'Комерційна пропозиція трансферу',
    confirmation_title: 'Підтвердження трансферу',
    offer_subtitle:
      'PDF з акцентом на маршрут, ціну та обсяг послуги до остаточного підтвердження.',
    confirmation_subtitle:
      'Підтверджений PDF з деталями поїздки, учасниками та сервісними умовами.',
    plan: 'План',
    price: 'Ціна',
    monthly_limit: 'Ліміт на місяць',
    document_quality: 'Рівень PDF',
    document_type: 'Тип документа',
    customer: 'Клієнт',
    driver: 'Водій',
    provider: 'Перевізник',
    pickup: 'Посадка',
    dropoff: 'Висадка',
    departure_time: 'Час виїзду',
    payment: 'Оплата',
    total: 'Сума',
    order_number: 'Номер замовлення',
    issue_date: 'Дата випуску',
    valid_until: 'Діє до',
    trip_overview: 'Огляд поїздки',
    parties: 'Учасники',
    service_scope: 'Що входить',
    service_terms: 'Сервісні умови',
    premium_operations: 'Premium operations',
    next_steps: 'Наступні кроки',
    signatures: 'Підписи',
    carrier_signature: 'Підпис перевізника',
    customer_signature: 'Підпис клієнта',
    support: 'Підтримка',
    reference_id: 'Reference ID',
    generated_by: 'Згенеровано бекендом DocTra',
    note: 'Примітка',
    offer: 'Пропозиція',
    confirmation: 'Підтвердження',
    essential: 'Базовий PDF',
    branded: 'Branded PDF',
    premium: 'Premium PDF',
    starter_offer_note:
      'Короткий offer-пакет для швидкого узгодження вартості, маршруту та часу.',
    starter_confirmation_note:
      'Компактне підтвердження для приватного водія або малого щоденного потоку.',
    growth_offer_note:
      'Брендований offer з розширеним summary для стабільної операційної роботи.',
    growth_confirmation_note:
      'Більш деталізоване підтвердження з service highlights та readiness block.',
    scale_offer_note:
      'Преміальний offer для командного або партнерського потоку з операційним контекстом.',
    scale_confirmation_note:
      'Розширений confirmation PDF з ops, legal та audit-ready блоками.',
    shared_scope_1: 'Маршрут, час виїзду та контакт клієнта',
    shared_scope_2: 'Вартість поїздки та спосіб оплати',
    shared_scope_3: 'Внутрішній reference/order ID для трекінгу',
    growth_scope_1: 'Виділений summary для партнера або dispatch',
    growth_scope_2: 'Service highlights і branded accent sections',
    scale_scope_1: 'Operations desk, service SLA та premium support note',
    scale_scope_2: 'Audit-ready reference block і expanded terms summary',
    offer_term_1: 'Ціна і маршрут зафіксовані на момент випуску документа.',
    offer_term_2: 'Зміна адреси або часу може змінити остаточну ціну.',
    offer_term_3: 'Підтвердження бронювання відбувається після погодження деталей.',
    confirmation_term_1: 'Трансфер підтверджено на погоджені дату, час і маршрут.',
    confirmation_term_2: 'Клієнт отримує сервіс згідно з даними цього документа.',
    confirmation_term_3: 'Зміни після підтвердження обробляються як окремий запит.',
    premium_term_1: 'Premium plan додає розширений operational context для команди.',
    premium_term_2: 'Документ придатний для внутрішнього audit trail та partner handoff.',
    next_step_offer_1: 'Погодити фінальний маршрут і контакт на день поїздки.',
    next_step_offer_2: 'Підтвердити оплату або умови розрахунку.',
    next_step_confirmation_1: 'Використати document reference для support або dispatch.',
    next_step_confirmation_2: 'Передати клієнту фінальну confirmation copy.',
    support_note_starter: 'Питання по бронюванню вирішуються напряму з перевізником.',
    support_note_growth: 'Growth PDF додатково підходить для branded handoff клієнту.',
    support_note_scale: 'Scale PDF розрахований на командну роботу, audit і premium support.',
  },
  en: {
    app_name: 'DocTra',
    offer_title: 'Transfer offer',
    confirmation_title: 'Transfer confirmation',
    offer_subtitle:
      'Offer PDF focused on route, pricing, and service scope before final confirmation.',
    confirmation_subtitle:
      'Confirmed PDF with trip details, parties, and service terms.',
    plan: 'Plan',
    price: 'Price',
    monthly_limit: 'Monthly limit',
    document_quality: 'Document quality',
    document_type: 'Document type',
    customer: 'Customer',
    driver: 'Driver',
    provider: 'Provider',
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    departure_time: 'Departure time',
    payment: 'Payment',
    total: 'Total',
    order_number: 'Order number',
    issue_date: 'Issue date',
    valid_until: 'Valid until',
    trip_overview: 'Trip overview',
    parties: 'Parties',
    service_scope: 'Service scope',
    service_terms: 'Service terms',
    premium_operations: 'Premium operations',
    next_steps: 'Next steps',
    signatures: 'Signatures',
    carrier_signature: 'Carrier signature',
    customer_signature: 'Customer signature',
    support: 'Support',
    reference_id: 'Reference ID',
    generated_by: 'Generated by DocTra backend',
    note: 'Note',
    offer: 'Offer',
    confirmation: 'Confirmation',
    essential: 'Essential PDF',
    branded: 'Branded PDF',
    premium: 'Premium PDF',
    starter_offer_note:
      'Compact offer package for quick pricing, routing, and timing alignment.',
    starter_confirmation_note:
      'Compact confirmation for a private driver or a small daily transfer flow.',
    growth_offer_note:
      'Branded offer with richer summary blocks for stable operational handoff.',
    growth_confirmation_note:
      'More detailed confirmation with service highlights and readiness sections.',
    scale_offer_note:
      'Premium offer for teams or partner traffic with extra operational context.',
    scale_confirmation_note:
      'Expanded confirmation PDF with ops, legal, and audit-ready sections.',
    shared_scope_1: 'Route, departure time, and customer contact details',
    shared_scope_2: 'Trip price and payment method',
    shared_scope_3: 'Internal reference/order ID for tracking',
    growth_scope_1: 'Dedicated summary block for partner or dispatch teams',
    growth_scope_2: 'Service highlights and branded accent sections',
    scale_scope_1: 'Operations desk, service SLA, and premium support note',
    scale_scope_2: 'Audit-ready reference block and expanded terms summary',
    offer_term_1: 'Price and route are fixed at the moment this document is issued.',
    offer_term_2: 'Any address or schedule change may affect the final price.',
    offer_term_3: 'Booking becomes final after the trip details are confirmed.',
    confirmation_term_1: 'The transfer is confirmed for the agreed date, time, and route.',
    confirmation_term_2: 'The customer receives the service exactly as listed here.',
    confirmation_term_3: 'Changes after confirmation are processed as a separate request.',
    premium_term_1: 'Premium plan adds extra operational context for team workflows.',
    premium_term_2: 'This document is suitable for internal audit trail and partner handoff.',
    next_step_offer_1: 'Confirm the final route and day-of-trip contact details.',
    next_step_offer_2: 'Confirm payment method or settlement terms.',
    next_step_confirmation_1: 'Use the document reference for support or dispatch.',
    next_step_confirmation_2: 'Share the final confirmation copy with the customer.',
    support_note_starter: 'Booking questions are handled directly with the carrier.',
    support_note_growth: 'Growth PDF is additionally suitable for branded client handoff.',
    support_note_scale:
      'Scale PDF is designed for team workflows, audit, and premium support.',
  },
  cs: {
    app_name: 'DocTra',
    offer_title: 'Nabidka transferu',
    confirmation_title: 'Potvrzeni transferu',
    offer_subtitle:
      'PDF nabidka z durazem na trasu, cenu a rozsah sluzby pred finalnim potvrzenim.',
    confirmation_subtitle:
      'Potvrzene PDF s detaily jizdy, ucastniky a servisnimi podminkami.',
    plan: 'Plan',
    price: 'Cena',
    monthly_limit: 'Mesicni limit',
    document_quality: 'Uroven PDF',
    document_type: 'Typ dokumentu',
    customer: 'Klient',
    driver: 'Ridic',
    provider: 'Dopravce',
    pickup: 'Nastup',
    dropoff: 'Vystup',
    departure_time: 'Cas odjezdu',
    payment: 'Platba',
    total: 'Celkem',
    order_number: 'Cislo objednavky',
    issue_date: 'Datum vystaveni',
    valid_until: 'Platne do',
    trip_overview: 'Prehled jizdy',
    parties: 'Ucastnici',
    service_scope: 'Rozsah sluzby',
    service_terms: 'Servisni podminky',
    premium_operations: 'Premium operations',
    next_steps: 'Dalsi kroky',
    signatures: 'Podpisy',
    carrier_signature: 'Podpis dopravce',
    customer_signature: 'Podpis klienta',
    support: 'Podpora',
    reference_id: 'Reference ID',
    generated_by: 'Vygenerovano backendem DocTra',
    note: 'Poznamka',
    offer: 'Nabidka',
    confirmation: 'Potvrzeni',
    essential: 'Zakladni PDF',
    branded: 'Branded PDF',
    premium: 'Premium PDF',
    starter_offer_note:
      'Kratky offer balik pro rychle sladeni ceny, trasy a casu.',
    starter_confirmation_note:
      'Kompaktni potvrzeni pro soukromeho ridice nebo mensi denni provoz.',
    growth_offer_note:
      'Branded offer s rozsirenym summary pro stabilni operacni provoz.',
    growth_confirmation_note:
      'Detailnejsi potvrzeni se service highlights a readiness blockem.',
    scale_offer_note:
      'Premiovy offer pro tymovy nebo partnersky provoz s operacnim kontextem.',
    scale_confirmation_note:
      'Rozsirene confirmation PDF s ops, legal a audit-ready sekcemi.',
    shared_scope_1: 'Trasa, cas odjezdu a kontakt klienta',
    shared_scope_2: 'Cena jizdy a zpusob platby',
    shared_scope_3: 'Interni reference/order ID pro tracking',
    growth_scope_1: 'Samostatny summary blok pro partnera nebo dispatch',
    growth_scope_2: 'Service highlights a branded accent sekce',
    scale_scope_1: 'Operations desk, service SLA a premium support note',
    scale_scope_2: 'Audit-ready reference blok a rozsireny terms summary',
    offer_term_1: 'Cena a trasa jsou fixovany v okamziku vystaveni dokumentu.',
    offer_term_2: 'Zmena adresy nebo casu muze ovlivnit finalni cenu.',
    offer_term_3: 'Rezervace je finalni po potvrzeni detailu jizdy.',
    confirmation_term_1: 'Transfer je potvrzen na dohodnute datum, cas a trasu.',
    confirmation_term_2: 'Klient obdrzi sluzbu presne podle tohoto dokumentu.',
    confirmation_term_3: 'Zmeny po potvrzeni se resi jako samostatny pozadavek.',
    premium_term_1: 'Premium plan pridava operacni kontext pro tymovy workflow.',
    premium_term_2: 'Dokument je vhodny pro interni audit trail a partner handoff.',
    next_step_offer_1: 'Potvrdit finalni trasu a kontakt pro den jizdy.',
    next_step_offer_2: 'Potvrdit platbu nebo podminky vyuctovani.',
    next_step_confirmation_1: 'Pouzijte reference dokumentu pro support nebo dispatch.',
    next_step_confirmation_2: 'Sdilejte finalni confirmation copy s klientem.',
    support_note_starter: 'Dotazy k rezervaci se resi primo s dopravcem.',
    support_note_growth:
      'Growth PDF je navic vhodne pro branded predani klientovi.',
    support_note_scale:
      'Scale PDF je navrzene pro tymovy workflow, audit a premium support.',
  },
};

export const THEME_TOKENS = {
  starter: {
    accent: '#b56e2d',
    accentSoft: '#f7eadc',
    accentStrong: '#7e4917',
    surface: '#fffaf5',
    border: '#e8c9aa',
    text: '#352416',
    muted: '#7c6b5c',
    hero: 'linear-gradient(135deg, rgba(181,110,45,0.18), rgba(255,255,255,0.88) 62%)',
  },
  growth: {
    accent: '#5d7590',
    accentSoft: '#e4edf7',
    accentStrong: '#30465f',
    surface: '#f8fbff',
    border: '#c8d6e5',
    text: '#1f3043',
    muted: '#5f7084',
    hero: 'linear-gradient(135deg, rgba(93,117,144,0.18), rgba(255,255,255,0.9) 62%)',
  },
  scale: {
    accent: '#c79a1d',
    accentSoft: '#fff3c7',
    accentStrong: '#7c5f12',
    surface: '#fffdf6',
    border: '#ead387',
    text: '#3c3214',
    muted: '#74663b',
    hero: 'linear-gradient(135deg, rgba(199,154,29,0.2), rgba(255,255,255,0.92) 60%)',
  },
};
