function escapePdfText(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function buildPdfBuffer(lines) {
  const textStream = [
    'BT',
    '/F1 12 Tf',
    '50 790 Td',
    '16 TL',
    ...lines.map(line =>
      line === '' ? 'T*' : `(${escapePdfText(line)}) Tj T*`
    ),
    'ET',
  ].join('\n');

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n',
    `4 0 obj\n<< /Length ${Buffer.byteLength(textStream, 'utf8')} >>\nstream\n${textStream}\nendstream\nendobj\n`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += object;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');

  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';

  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}

export function createContractPdf(contractData = {}) {
  const lines = [
    'TransferDocs Contract',
    '',
    `Order number: ${contractData.orderNumber || '-'}`,
    `Issue date: ${contractData.today || '-'}`,
    '',
    `Driver: ${contractData.driver?.name || '-'}`,
    `Provider: ${contractData.provider?.name || '-'}`,
    '',
    `Customer: ${contractData.customer?.name || '-'}`,
    `Customer email: ${contractData.customer?.email || contractData.customer?.phone || '-'}`,
    '',
    `Pickup: ${contractData.trip?.from?.address || '-'}`,
    `Dropoff: ${contractData.trip?.to?.address || '-'}`,
    `Trip time: ${contractData.trip?.time || '-'}`,
    `Payment: ${contractData.trip?.paymentMethod || '-'}`,
    `Total: ${contractData.totalPrice || '-'}`,
    '',
    'Generated by TransferDocs backend',
  ];

  return buildPdfBuffer(lines);
}
