export const refs = {
  ordersDateFilter: document.getElementById('ordersDateFilter'),
  ordersDateFilterLabel: document.getElementById('ordersDateFilterLabel'),
  ordersList: document.getElementById('ordersList'),
  ordersEmpty: document.getElementById('ordersEmpty'),
  orderDetailModal: document.getElementById('orderDetailModal'),
  orderDetailBackdrop: document.getElementById('orderDetailBackdrop'),
  orderDetailCloseBtn: document.getElementById('orderDetailCloseBtn'),
  orderDetailNumber: document.getElementById('orderDetailNumber'),
  orderDetailCustomer: document.getElementById('orderDetailCustomer'),
  orderDetailRoute: document.getElementById('orderDetailRoute'),
  orderDetailDate: document.getElementById('orderDetailDate'),
  orderDetailStatus: document.getElementById('orderDetailStatus'),
  orderDetailTotal: document.getElementById('orderDetailTotal'),
  orderDetailPdf: document.getElementById('orderDetailPdf'),
  orderDetailDocumentType: document.getElementById('orderDetailDocumentType'),
  orderDetailOfferBtn: document.getElementById('orderDetailOfferBtn'),
  orderDetailConfirmationBtn: document.getElementById('orderDetailConfirmationBtn'),
  orderDetailTitle: document.getElementById('orderDetailTitle'),
  orderDetailCustomerEmail: document.getElementById('orderDetailCustomerEmail'),
  orderDetailPickup: document.getElementById('orderDetailPickup'),
  orderDetailDropoff: document.getElementById('orderDetailDropoff'),
  orderDetailTripTime: document.getElementById('orderDetailTripTime'),
  orderDetailPayment: document.getElementById('orderDetailPayment'),
  orderDetailIssueDate: document.getElementById('orderDetailIssueDate'),
};
