export const state = {
  ordersDateFilter: '',
  orderDetailOrderId: '',
  orderActionsOrderId: '',
  orderActionsOrder: null,
  orderActionsOrigin: '',
  orderActionsVisible: false,
  orderActionsLoading: false,
  orderActionsError: '',
  orderTransferVisible: false,
  orderTransferUsers: [],
  orderTransferSearch: '',
  orderTransferLoading: false,
  orderTransferSubmitting: false,
  orderTransferError: '',
  orderTransferLoaded: false,
  orderTransferRequestId: 0,
  orderTransferSelectedUserId: '',
  orderTransferSelectedUser: null,
};
